// Code generated by protoc-gen-go. DO NOT EDIT.
// source: codec/internal/fixtures/protobuf.proto

package fixtures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ProtoMessage is a Dogma message implemented as a Protocol Buffers message.
type ProtoMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoMessage) Reset()         { *m = ProtoMessage{} }
func (m *ProtoMessage) String() string { return proto.CompactTextString(m) }
func (*ProtoMessage) ProtoMessage()    {}
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8d2f9defb5f2ef5, []int{0}
}

func (m *ProtoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMessage.Unmarshal(m, b)
}
func (m *ProtoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMessage.Marshal(b, m, deterministic)
}
func (m *ProtoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMessage.Merge(m, src)
}
func (m *ProtoMessage) XXX_Size() int {
	return xxx_messageInfo_ProtoMessage.Size(m)
}
func (m *ProtoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMessage proto.InternalMessageInfo

func (m *ProtoMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtoMessage)(nil), "dogmatiq.marshalkit.fixtures.ProtoMessage")
}

func init() {
	proto.RegisterFile("codec/internal/fixtures/protobuf.proto", fileDescriptor_b8d2f9defb5f2ef5)
}

var fileDescriptor_b8d2f9defb5f2ef5 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xce, 0x4f, 0x49,
	0x4d, 0xd6, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0xcb, 0xac, 0x28, 0x29,
	0x2d, 0x4a, 0x2d, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x03, 0x33, 0x84,
	0x64, 0x52, 0xf2, 0xd3, 0x73, 0x13, 0x4b, 0x32, 0x0b, 0xf5, 0x72, 0x13, 0x8b, 0x8a, 0x33, 0x12,
	0x73, 0xb2, 0x33, 0x4b, 0xf4, 0x60, 0x8a, 0x95, 0x54, 0xb8, 0x78, 0x02, 0x40, 0xca, 0x7c, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x27, 0x8b, 0x28, 0xb3, 0xf4, 0xcc, 0x92, 0x8c, 0xd2,
	0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x98, 0x81, 0xfa, 0x08, 0x03, 0xf5, 0x71, 0x38, 0x26, 0x89,
	0x0d, 0xec, 0x08, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x83, 0xd3, 0xe8, 0xae, 0x00,
	0x00, 0x00,
}
